In [1]:
import numpy as np
import pandas as pd
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [2]:
import drGAT

# model evaluation

In [3]:
test = torch.load("test.pt")

In [4]:
test

[tensor([[1.0000, 0.9683, 0.9683,  ..., 0.9394, 0.9603, 0.9575],
         [0.9683, 1.0000, 0.9932,  ..., 0.9477, 0.9659, 0.9650],
         [0.9683, 0.9932, 1.0000,  ..., 0.9514, 0.9697, 0.9688],
         ...,
         [0.9394, 0.9477, 0.9514,  ..., 1.0000, 0.9472, 0.9500],
         [0.9603, 0.9659, 0.9697,  ..., 0.9472, 1.0000, 0.9598],
         [0.9575, 0.9650, 0.9688,  ..., 0.9500, 0.9598, 1.0000]]),
 tensor([[1.0000, 0.0170, 0.0069,  ..., 0.4732, 0.0140, 0.2338],
         [0.0170, 1.0000, 0.4351,  ..., 0.0421, 0.4509, 0.0916],
         [0.0069, 0.4351, 1.0000,  ..., 0.0196, 0.2926, 0.0337],
         ...,
         [0.4732, 0.0421, 0.0196,  ..., 1.0000, 0.0267, 0.3622],
         [0.0140, 0.4509, 0.2926,  ..., 0.0267, 1.0000, 0.0919],
         [0.2338, 0.0916, 0.0337,  ..., 0.3622, 0.0919, 1.0000]]),
 tensor([[1., 0., 0.,  ..., 0., 0., 0.],
         [0., 1., 0.,  ..., 0., 0., 0.],
         [0., 0., 1.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 1., 0., 0.],
         [

In [5]:
tmp = !ls | grep pt
model = torch.load("sample.pt", map_location=device)

In [6]:
predict, res = drGAT.eval(model, test)  # Probability of sensitivity and Metrics
res

Accuracy  Precision    Recall  F1 Score  True Positive  True Negative  \
0  0.771375   0.740881  0.783245  0.761474           1178           1312   

   False Positive  False Negative  
0             412             326

In [7]:
predict

tensor([0.7653, 0.3292, 0.3037,  ..., 0.9121, 0.4277, 0.2037])

# For single drug and cell line

In [8]:
test[4] = np.array([9])  # drug index
test[5] = np.array([292])  # cell index
test[6] = torch.tensor([1])  # label
test

[tensor([[1.0000, 0.9683, 0.9683,  ..., 0.9394, 0.9603, 0.9575],
         [0.9683, 1.0000, 0.9932,  ..., 0.9477, 0.9659, 0.9650],
         [0.9683, 0.9932, 1.0000,  ..., 0.9514, 0.9697, 0.9688],
         ...,
         [0.9394, 0.9477, 0.9514,  ..., 1.0000, 0.9472, 0.9500],
         [0.9603, 0.9659, 0.9697,  ..., 0.9472, 1.0000, 0.9598],
         [0.9575, 0.9650, 0.9688,  ..., 0.9500, 0.9598, 1.0000]]),
 tensor([[1.0000, 0.0170, 0.0069,  ..., 0.4732, 0.0140, 0.2338],
         [0.0170, 1.0000, 0.4351,  ..., 0.0421, 0.4509, 0.0916],
         [0.0069, 0.4351, 1.0000,  ..., 0.0196, 0.2926, 0.0337],
         ...,
         [0.4732, 0.0421, 0.0196,  ..., 1.0000, 0.0267, 0.3622],
         [0.0140, 0.4509, 0.2926,  ..., 0.0267, 1.0000, 0.0919],
         [0.2338, 0.0916, 0.0337,  ..., 0.3622, 0.0919, 1.0000]]),
 tensor([[1., 0., 0.,  ..., 0., 0., 0.],
         [0., 1., 0.,  ..., 0., 0., 0.],
         [0., 0., 1.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 1., 0., 0.],
         [

In [9]:
# Probability of sensitivity.
predict, _ = drGAT.eval(model, test)
predict

tensor(0.7653)